uvicgse/project-virtual-team-1

app/misc/authenticate.ts
#9 The "No Internet Connection" error messages are triggered by a specific error message returned from the Github API. This error message is different on windows and mac so I added a check for each. Given that there is no internet connection we aren't able to check http error codes. I also future proofed it slightly by only checking for the relevant part of the error message.
=> Issue #9 fixing error message for no internet

index.js
I removed the  inappropriate log message for bug-issue10, The "registration failed " messaged was removed because it served no purpose and was initially added for testing reasons.
=> removed inappropriate log message for bug-issue10

.npmrc, README.md, app/misc/color.ts, app/misc/git.ts, index.js, package-lock.json, package.json
Upgrade of Electron to version 5 and the latest Node version resolves this file system dialog issue. Installation of Python 2 is required for rebuilding native node modules as part of this upgrade (https://github.com/uvicgse/project-virtual-team-1/wiki/Upgrade-Process)
=> Fix Issue #26: Upgrade Electron and Node versions

app/misc/authenticate.ts
check the err object for a statuscode and if it is 401 (unauthorized) show an appropriate dialog to the users.
I also made all the {} in this block consistent with each other.
=> Issue 14 invalid creds shows unclear error

app/misc/git.ts, app/misc/repo.ts
This should fix the problem caused by concating 'Branch: ' label with real branch name.
=> fixed problem with get current branch name after added label 'Branch: '

app/misc/authenticate.ts
I added some comments to the code regarding my change.
Please ignore all the whitespace changes.
=> add some comments to provide more information regarding the http 401 error

app/misc/repo.ts, index.html, stylesheets/styles.css
- added a new live-reload feature for keeping dropdown list up-to-date.
- fixed style issue of the dropdown list outline.
- clearBranchElement() now becomes clearBranchAndTagElement()
my implementation to the live-reload:
- add a monitor to track the list of reference(branch and tag), once it detects change to the list, it will refresh the list.
- the monitor tracks list every one second.
=> Issue #66: live-reload function for dropdown list - New feature

app/misc/git.ts, package.json
Quick merge of fixes back to original branch
=> Fixed unused packages, add command, error handling

app/misc/git.ts, index.js
This pull request resolves the issue with the graph not updating after committing a change. The problem was found in the `addAndCommit()` function in `app/misc/git.ts`, which was calling unused functions at the end of its run that was blocking the graph update functions from running. We commented out the functions but left them there in case they are needed in future implementations.
Expected behaviour now is once you commit a change, the graph will update and show a new node for the new commit.
=> Issue 7 Graph won't update after commit

app/components/header/header.component.html, app/misc/git.ts, package-lock.json, stylesheets/styles.css
Issue #106: adding the ability stash untracked files
1.) add a checkbox
2.) if the checkbox is checked, pass in the untracked files flag.
=> issue #106: add the ability to stash untracked files

app/misc/graphing.ts, app/misc/repo.ts, index.html
This solves #29 and #101.
White nodes should no longer appear when committing or when refreshing the graph.
=> Bug 29 investigate white nodes

app/components/filePanel/file.panel.component.html, app/misc/git.ts, app/misc/repo.ts, index.html, stylesheets/styles.css
#87 Stash list displays and live updates with all current stashes. Should update similarly to the staged files list. Also allows for popping the top stash in the list as per #88 , pop button should hide on if there are no stashes to pop.
=> Issue 87 allow a user to view stash list

app/misc/git.ts, app/misc/repo.ts
Fixed problem @colinwerner found with git stash secretly adds a hidden reference `refs/stash`.
Fixed problem when open a second repo showing alert message problem.
=> fixed stash branch problem. fixed reopen repo showing up alert problem

app/misc/git.ts
now when you use the console in VG you don't see the log lines repeating
=> comment out a couple console.log lines that were printing too often

app/components/addRepository/add.repository.component.ts, app/main.ts
its a workaround.
i did spend around 2 hours trying to fix tsconfig.file so that these error wont come but not able to reduce to 0. the minimum was 235 errors!
so, for now, added this dummy real error.
=> Work around for the tsc errors on npm start

app/components/diffPanel/diff.panel.component.html, app/components/textEditor/text.editor.component.html, app/components/textEditor/text.editor.component.ts, app/misc/git.ts
This feature adds file rename and move buttons the file editor panel and allows a user to rename or move any file in the repository, as described in issue #125.
=> Feature 125 move or rename any file

app/components/header/header.component.html, app/misc/graphing.ts, index.html, stylesheets/styles.css
Icons are now larger and the repo path element does not stack upon window resizing. Also, made the font of the repo path smaller and the right arrows are now fontawesome. Shout out to @hdauvic for help with the graph icons!
Give this a test and share the bugs!
=> Issue 177 navbar upgrade

app/components/addRepository/add.repository.component.html, app/components/header/header.component.html, app/misc/router.ts
There were a couple ways to go about doing this, this was the simpliest.
Basically, only show the repo thing and the navbar when there is a repo path.
=> only show the repo thing and the navbar when there is a repo path

app/components/header/header.component.html, app/misc/git.ts
- User should be able to commit from navbar
-Clicking on the commit button should open a commit modal
-User should be able to enter a message and commit their changes
=> Issue 175 commit functionality from navbar

app/components/header/header.component.html, app/misc/git.ts
We have implemented the basic functionality for `git rebase`.  Dropdown menus have been populated with both local and remote branches which can be selected for the rebase.  The implementation was done using `simple-git` since the `nodegit` alternative was not working correctly for us.
=> Basic Rebasing Functionality
