app/misc/git.ts
Fixed Issue #47, which only occurred on non-Windows platforms.
The root cause of the issue is that a '/' was being used in the file path, which is not understood by *NIX.
I used the path.join library to make the path, which knows whether to use a '/' or a '\'.
=> Fix Issue #47: do not use '//' as this won't work on *NIX, so use path.join instead

stylesheets/styles.css
The "file editor" text stays inside the button and those three buttons at the footer doesn't disappear in the left side for a smaller window size.
Stopped the white space from getting wrapped and fixed the position of the three footer buttons so they don't disappear on the left side for smaller windows
=> CSS fix for the editor button (issue #74)

app/components/header/header.component.html, stylesheets/styles.css
The issue here seemed to be with the bootstrap grid system having a four-column width, which messed with the icons upon resize. Issue #8
=> Issue 8 - Navbar Icons Adjusting Irregularly

app/misc/authenticate.ts, app/misc/git.ts
Solves Issue 71: pulling or pushing the 2nd time crashes the application. It looks like GitHub no longer let you use the same credentials object for different request requiring authentication. And hence we are creating and using a new object every time.
Solves Issue 72: in case of error occur during pull or push it shows that error message to the user. there was no catch in the process. (there was on in pull but at the wrong place) .
Solves new issue: errors during a pull cause the application to crash. for example, pull when there is no internet will crash the application with low-level assertion fail error. this issue is considered part of issue 72.
Note: no custom messages are created. the messages from the server are directly shown to the users.
=> Issue 71 & 72 : double pull or push crash fix and  error handling

app/components/graphPanel/graph.panel.component.html, app/components/graphPanel/graph.panel.component.ts, app/misc/git.ts, app/misc/graphing.ts, app/misc/repo.ts, index.html, stylesheets/styles.css
Feature:
- Added a button to allow user refresh commit graph at any time.
- Commit graph can auto detects changes in number of commits in the repo and alert user.
Fix:
- This PR also fixed problem where when at second level zoom, tags and branches are missing in non-HEAD commit.
Design logic:
- From user's point of view, when commit graph detects any changes(whether new tag or branch has been created or new commits has been made), a yellow warning banner will show up with button to allow user to refresh the graph.
- How I achieved this: 1) periodic checks on tag and branch list changes and changes in number of commit current branch has. 2) once detects change, it pops up a banner to tell user that the commit graph is outdated and could be refreshed by pressing the refresh button.
How to …
=> ISSUE#105: Allow user to refresh commit graph when detects local repo changes

app/misc/repo.ts, stylesheets/styles.css
This feature allows you to delete a tag from the tag list. 
**Implementation** 
- The CSS for implementing a button within the list items for the tags was very ugly, so I implemented the ability to double click to delete tag. 
- Upon a single click, a modal pops up to let the user know that they can double click on a tag to delete it. After this first click, the modal doesn't appear anymore. 
- The changes in the tag list are reflected immediately but the graph is not updated. Issue #105 covers that scope. 
Note: there is a minor bug where you cannot delete tag names with periods in them. This is due to JS being unable to handle function passing of strings with periods in the name. I can open an issue for this for further investigation and am open to suggestions on how to fix it.
=> Feature 56 - delete a tag 

stylesheets/styles.css
Fixes issue #102  - navbar icon text was left aligned and then switched to center align on hover. Now always centered
=> Issue 102 - Fix Icon Text Alignment

app/components/graphPanel/graph.panel.component.html, app/components/pullRequestPanel/pull.request.panel.component.html, app/misc/git.ts, index.html, package-lock.json
I recloned master and copied the unpushed commits functions, however for the getallpushed commit function I rewrote it a bit different. 
This PR adds functionality to allow the user to view the total number of un-pushed commits. We calculate the current number of local commits and the current number of remote commits using nodegit calls and then take the difference. We have done this by adding new functions in the app/misc/git.ts file.
We cannot distinguish the un-pushed commits by IDs using nodegit, so the next best thing would be to show the user the count of un-pushed commits. Issues for adding log-type support to nodegit are currently open. simple-git was added to the project later into this sprint, so we didn't have time to test out its logging functions for our issue. This may be …
=> Issue -70 - recloned master and updated unpushed commits count

app/misc/graphing.ts
Added clear comments to full file; please review my comments for spelling errors.
Created clear images to differentiate between tags and branches, as well as removing arrows pointing to commits for tags, and changed their lines to be dashed instead of solid to further differentiate them.
I attempted to create boxes with the tags/branch names and an icon within them, but this proved too difficult to fulfill due to limitations with the html/svg communication within the program itself.
=> Tags and Branches have different images.

app/misc/color.ts
This is a very simple change. Upon startup the system tries to change the theme to whatever is provided in the user_color file, but since with the OAuth changes there is no rememberLogin element anymore, it errors out and never completes the task. Resulting in continuous errors in the console log.
This PR just removes any attempts to change the rememberLogin checkbox style.
=> Removed code for changing rememberLogin color.

app/misc/graphing.ts, app/misc/images.ts
This PR implements #31. 
In addition, GitHub profile pictures are now also available in the popup that appears when clicking on a node:
In order to retrieve a user's profile picture through the GitHub API, the username is required. However, because usernames are a GitHub concept - Git works with full names and emails, as supplied via `git config user.name` and `user.email` - **GitHub usernames are scraped from `@users.noreply.github.com` emails if available**. Consequently, profile pictures are unavailable for users that did not hide their email in their GitHub settings and set their Git `user.email` to their `noreply` email ([more info here](https://help.github.com/en/articles/about-commit-email-addresses)).
Letter icons will continue to be used if a profile picture is unavailable.
There …
=> Issue 31: GitHub profile pictures on nodes

app/components/addRepository/add.repository.component.html, app/misc/repo.ts
Fixed:
- issue #127 where the repo name won't show up when open from a local repository.
Investigation reason: 
- the script tries to get path from webkitRelativePath which is an empty string as shown in the figure below.
- this likely is because angular 2 doesn't support `webkitdirectory`.
Solution:
- use regular expression to get directory name
After:
=> Issue#127 repo doesn't show up on the nav bar

app/misc/git.ts
the newline message has an additional newline character in it, so just replace it with the new line message
ie replace "<	12	<	\n\ No newline at end of file\n"
with "\ No newline at end of file"
as per git CLI:
test-merge $ git diff AnotherFile.txt
diff --git a/AnotherFile.txt b/AnotherFile.txt
index 56c23e5..1999256 100644
--- a/AnotherFile.txt
+++ b/AnotherFile.txt
@@ -5,4 +5,8 @@ sadf
asdf
asdf
asdf
-asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf
\ No newline at end of file
+asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf
+asdf
+asdf
+asdf
+asdf
\ No newline at end of file
=> Issue #1 line number repeated in diff file

app/components/pullRequestPanel/pull.request.panel.component.html, app/misc/authenticate.ts, package-lock.json, stylesheets/styles.css
Issue #178  This PR changes the colors of the Ahead and Behind badges to match the highlight colors of the unpushed commit nodes in the graph. Ahead is colored red to match the highlight color, and Behind is colored blue to contrast the red (it isn't currently used for anything other than a reference).
Also added a feature where, on hover, the cursor changes to a specified icon. So for hovering on Ahead, the cursor will change to the push icon to tell the user they may want to push. Conversely, hovering on Behind will change the cursor to the pull icon.
=> Feature 178 Update Unpushed Commit Highlight Colours

app/misc/graphing.ts
Really basic fix. In a new repo there are no commits so when loading a graph we need to test that there is a commit before trying to center on the first commit.
=> Ensured there is a commit to center on before centering.

app/components/filePanel/file.panel.component.html, app/components/graphPanel/graph.panel.component.html, app/components/graphPanel/graph.panel.component.ts, app/misc/git.ts, app/misc/graphSetup.ts, stylesheets/styles.css
This PR fixes:- 
#171 correct message on successful commit
#179 if we have too many files in the file-changed section it was a mess. fixed!
#180 checkbox for the files are now infront of them aligned to text. Note: file block size is still large to look prity. (i checked small does not look that cool and will create an uneven block in case of the large filename)
#187 as shown during planing the panels on both sides of the graph were little shorter then needed.fixed!
also #181 , you can now right-click an unpushed commit to undo the latest commit from that branch. 
Note: right-clicking on pushed commit does not have the undo option.
@jtiz003  demo for 181:- https://youtu.be/YXY0OlDC4ks
=> UI fixes for issue #171 ,#179 ,#180 ,#187  and feature to undo latest unpush commit.

app/components/app/app.component.ts, app/components/textEditor/text.editor.component.ts, app/misc/authenticate.ts, app/misc/color.ts, app/misc/git.ts, app/misc/graphSetup.ts, app/misc/graphing.ts, app/misc/images.ts, app/misc/repo.ts, app/misc/router.ts, app/misc/storeCredentials.ts, app/misc/wiki.ts, index.html
This PR solves #176 , the specified line codes seem to have been a legacy issue and long out of date. The hard coded line numbers have been removed, and the error is printed to the debugging console - it will be up to future developers to trace the issue themselves if that error is ever thrown. 
This PR also solves #4 as I found the culprits for the repeated printing of the unnecessary log and have commented them out with an additional comment above them if future devs want to use those for debugging.
I also commented out the repetitive `url of repo` log, this console line was overwhelming at times if the user has copious amounts of repos associated with their username. Again, a comment was added to inform future dev's of this choice. While this solves the pictured issue in #20 it does …
=> Editing errors for consistency

app/misc/repo.ts
Empty progress bar now is removed if a repo clone fails.
I also fixed an issue I found where there are two calls to refreshAll() when cloning. I couldn't find any reason there would be so I removed one.
=> Hid repo clone progress bar upon failure.

app/components/footer/footer.component.html, app/components/header/header.component.html, app/misc/dragAndDrop.ts, app/misc/git.ts, app/misc/keyboardShortcuts.ts, app/misc/router.ts, index.html, stylesheets/styles.css
This PR adds a few things for #186.
- Drag and drop to commit! You can now commit by dragging the commit box onto the graph
- Keyboard shortcut to commit, for the power users out there ctrl+enter will also activate the commit process.
- Commit button redesign, since the other 2 buttons are now gone the commit button looked weird on it's own
- Commit panel now disables when there are no staged files, this gives a better visual indicator of when you can and can't commit
- Lastly window.alert was causing issues with the drag and drop and was not in line with the rest of the project, this was brought in line with the rest of the project by using displaymodal instead
=> Feature 186 drag/drop to commit

app/components/header/header.component.html, app/misc/git.ts
Fixes #172: Previously, in order to edit the upstream repo you had to manually delete the upstream before entering the url of the new upstream. Now, if you have an upstream configured and enter a new one, a confirmation modal will appear and ask if you want to edit the upstream.
=> Issue 172 - Edit Upstream Repo
